// <auto-generated />
using System;
using DoAn_Web.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAn_Web.Migrations
{
    [DbContext(typeof(RecruitmentSystemContext))]
    [Migration("20251222214332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAn_Web.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__719FE4E85095AB1B");

                    b.HasIndex(new[] { "Email" }, "UQ__Admins__A9D1053400F486A2")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DoAn_Web.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime?>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("JobID");

                    b.Property<string>("ResumeUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ApplicationId")
                        .HasName("PK__Applicat__C93A4F7913F8B7FF");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "JobId", "StudentId" }, "UC_JobStudent")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "idx_ApplicationStatus");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("DoAn_Web.Models.ApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Approval__3214EC077D38655D");

                    b.HasIndex("JobId");

                    b.ToTable("ApprovalHistory", (string)null);
                });

            modelBuilder.Entity("DoAn_Web.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CompanyId")
                        .HasName("PK__Companie__2D971C4CAA3C5901");

                    b.HasIndex(new[] { "TaxCode" }, "UQ__Companie__12945A28F1C72148")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Companie__A9D105341070757D")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "idx_CompanyName");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DoAn_Web.Models.CompanyEvaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationId"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("CriteriaCompliance")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("CriteriaRelationship")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("CriteriaTaskPerformance")
                        .HasColumnType("decimal(3,1)");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int")
                        .HasColumnName("InternshipID");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("EvaluationId")
                        .HasName("PK_CompanyEvaluations");

                    b.HasIndex("InternshipId")
                        .IsUnique();

                    b.ToTable("CompanyEvaluations");
                });

            modelBuilder.Entity("DoAn_Web.Models.ExperienceLevel", b =>
                {
                    b.Property<int>("LevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LevelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LevelId")
                        .HasName("PK__Experien__09F03C06B75D802C");

                    b.HasIndex(new[] { "Name" }, "UQ__Experien__737584F69D146EA7")
                        .IsUnique();

                    b.ToTable("ExperienceLevels");
                });

            modelBuilder.Entity("DoAn_Web.Models.Internship", b =>
                {
                    b.Property<int>("InternshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InternshipId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternshipReportUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("InternshipId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Internships");
                });

            modelBuilder.Entity("DoAn_Web.Models.Interview", b =>
                {
                    b.Property<int>("InterviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InterviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InterviewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnlineLink")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Result")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("InterviewId")
                        .HasName("PK__Intervie__C97C5832B9354D02");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("DoAn_Web.Models.JobPosting", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<DateTime>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int")
                        .HasColumnName("JobTypeID");

                    b.Property<int>("LevelId")
                        .HasColumnType("int")
                        .HasColumnName("LevelID");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Vacancies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("JobId")
                        .HasName("PK__JobPosti__056690E2335C22CF");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("LevelId");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "Title" }, "idx_JobTitle");

                    b.ToTable("JobPostings");
                });

            modelBuilder.Entity("DoAn_Web.Models.JobType", b =>
                {
                    b.Property<int>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobTypeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JobTypeId")
                        .HasName("PK__JobTypes__E1F4624D6814BF47");

                    b.HasIndex(new[] { "Name" }, "UQ__JobTypes__737584F62860435D")
                        .IsUnique();

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("DoAn_Web.Models.LegalBase", b =>
                {
                    b.Property<int>("LegalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalID"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegalID");

                    b.ToTable("LegalBases");
                });

            modelBuilder.Entity("DoAn_Web.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA4775C7DA5D7");

                    b.HasIndex(new[] { "City", "Country" }, "UC_CityCountry")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DoAn_Web.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32B7D83E7F");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DoAn_Web.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA091E7F4A7D538");

                    b.HasIndex(new[] { "Name" }, "UQ__Skills__737584F6EF42AF77")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("DoAn_Web.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GitHubProfile")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Gpa")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("GPA");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52A796631424E");

                    b.HasIndex(new[] { "StudentCode" }, "UQ__Students__1FC88604308920C0")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentCode" }, "idx_StudentCode");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DoAn_Web.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupervisorId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SupervisorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("DoAn_Web.Models.SupervisorEvaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EvaluationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluationID"));

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int")
                        .HasColumnName("InternshipID");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("EvaluationID")
                        .HasName("PK_SupervisorEvaluations");

                    b.HasIndex("InternshipId")
                        .IsUnique();

                    b.ToTable("SupervisorEvaluations");
                });

            modelBuilder.Entity("DoAn_Web.Models.WeeklyReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("InternshipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupervisorComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("InternshipId");

                    b.ToTable("WeeklyReports");
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("JobID");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.HasKey("JobId", "SkillId")
                        .HasName("PK__JobSkill__689C99FC8E1DCDF3");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills", (string)null);
                });

            modelBuilder.Entity("StudentSkill", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("SkillID");

                    b.HasKey("StudentId", "SkillId")
                        .HasName("PK__StudentS__5F3F2367CC559E16");

                    b.HasIndex("SkillId");

                    b.ToTable("StudentSkills", (string)null);
                });

            modelBuilder.Entity("DoAn_Web.Models.Application", b =>
                {
                    b.HasOne("DoAn_Web.Models.JobPosting", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__JobID__6383C8BA");

                    b.HasOne("DoAn_Web.Models.Student", "Student")
                        .WithMany("Applications")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Stude__6477ECF3");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DoAn_Web.Models.ApprovalHistory", b =>
                {
                    b.HasOne("DoAn_Web.Models.JobPosting", "Job")
                        .WithMany("ApprovalHistories")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_ApprovalHistory_JobPostings");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DoAn_Web.Models.CompanyEvaluation", b =>
                {
                    b.HasOne("DoAn_Web.Models.Internship", "Internship")
                        .WithOne("CompanyEvaluation")
                        .HasForeignKey("DoAn_Web.Models.CompanyEvaluation", "InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CompanyEvaluations_Internships");

                    b.Navigation("Internship");
                });

            modelBuilder.Entity("DoAn_Web.Models.Internship", b =>
                {
                    b.HasOne("DoAn_Web.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_Web.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAn_Web.Models.Supervisor", "Supervisor")
                        .WithMany("Internships")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DoAn_Web.Models.Interview", b =>
                {
                    b.HasOne("DoAn_Web.Models.Application", "Application")
                        .WithMany("Interviews")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Interview__Appli__6A30C649");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("DoAn_Web.Models.JobPosting", b =>
                {
                    b.HasOne("DoAn_Web.Models.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__JobPostin__Compa__5629CD9C");

                    b.HasOne("DoAn_Web.Models.JobType", "JobType")
                        .WithMany("JobPostings")
                        .HasForeignKey("JobTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__JobPostin__JobTy__571DF1D5");

                    b.HasOne("DoAn_Web.Models.ExperienceLevel", "Level")
                        .WithMany("JobPostings")
                        .HasForeignKey("LevelId")
                        .IsRequired()
                        .HasConstraintName("FK__JobPostin__Level__5812160E");

                    b.HasOne("DoAn_Web.Models.Location", "Location")
                        .WithMany("JobPostings")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__JobPostin__Locat__59063A47");

                    b.Navigation("Company");

                    b.Navigation("JobType");

                    b.Navigation("Level");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DoAn_Web.Models.SupervisorEvaluation", b =>
                {
                    b.HasOne("DoAn_Web.Models.Internship", "Internship")
                        .WithOne("SupervisorEvaluation")
                        .HasForeignKey("DoAn_Web.Models.SupervisorEvaluation", "InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SupervisorEvaluations_Internships");

                    b.Navigation("Internship");
                });

            modelBuilder.Entity("DoAn_Web.Models.WeeklyReport", b =>
                {
                    b.HasOne("DoAn_Web.Models.Internship", "Internship")
                        .WithMany("WeeklyReports")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Internship");
                });

            modelBuilder.Entity("JobSkill", b =>
                {
                    b.HasOne("DoAn_Web.Models.JobPosting", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__JobSkills__JobID__5BE2A6F2");

                    b.HasOne("DoAn_Web.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__JobSkills__Skill__5CD6CB2B");
                });

            modelBuilder.Entity("StudentSkill", b =>
                {
                    b.HasOne("DoAn_Web.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentSk__Skill__4F7CD00D");

                    b.HasOne("DoAn_Web.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__StudentSk__Stude__4E88ABD4");
                });

            modelBuilder.Entity("DoAn_Web.Models.Application", b =>
                {
                    b.Navigation("Interviews");
                });

            modelBuilder.Entity("DoAn_Web.Models.Company", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("DoAn_Web.Models.ExperienceLevel", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("DoAn_Web.Models.Internship", b =>
                {
                    b.Navigation("CompanyEvaluation");

                    b.Navigation("SupervisorEvaluation");

                    b.Navigation("WeeklyReports");
                });

            modelBuilder.Entity("DoAn_Web.Models.JobPosting", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("ApprovalHistories");
                });

            modelBuilder.Entity("DoAn_Web.Models.JobType", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("DoAn_Web.Models.Location", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("DoAn_Web.Models.Student", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DoAn_Web.Models.Supervisor", b =>
                {
                    b.Navigation("Internships");
                });
#pragma warning restore 612, 618
        }
    }
}
